/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;

/**
 *
 * @author User
 */
public class MainWinClient extends javax.swing.JFrame {

    private int choose;
    private Socket mainSocket;
    private ObjectInputStream in;
    private ObjectOutputStream out;
    private WinInput mainInputPanel;

    private static int mainWidth = 500;
    private static int mainHeight = 400;

    /**
     * Creates new form MainWinClient
     */
    public MainWinClient() throws IOException {

        initComponents();
        this.setResizable(false);
        computeBtn.setVisible(false);
        choose = 0;

        InetAddress addr = InetAddress.getByName("localhost");
        System.out.println("addr = " + addr + "\nport=" + 5000);

        try {
            mainSocket = new Socket(addr, 5000);

        } catch (java.net.ConnectException e) {
            JOptionPane.showMessageDialog(null, "Connessione assente", "Errore", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }

        out = new ObjectOutputStream(mainSocket.getOutputStream());
        in = new ObjectInputStream(mainSocket.getInputStream());

        mainInputPanel = new WinInput(in, out);
        mainInputPanel.setVisible(false);

        out.writeObject('s');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        mainTitle = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        newEP = new javax.swing.JRadioButton();
        fileEP = new javax.swing.JRadioButton();
        computeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setPreferredSize(new java.awt.Dimension(500, 400));

        mainTitle.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(30, 0, 255));
        mainTitle.setText("Benvenuto in EpMiner!");

        startLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        startLabel.setText("   Inizia!");

        startGroup.add(newEP);
        newEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        newEP.setText("Nuova scoperta");
        newEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEPActionPerformed(evt);
            }
        });

        startGroup.add(fileEP);
        fileEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fileEP.setText(" Risultati in archivio");
        fileEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileEPActionPerformed(evt);
            }
        });

        computeBtn.setText("VAI!");
        computeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newEP, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(startLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(238, 238, 238))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileEP)
                    .addComponent(computeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(mainTitle)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newEP)
                .addGap(30, 30, 30)
                .addComponent(fileEP)
                .addGap(67, 67, 67)
                .addComponent(computeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newEPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newEPActionPerformed
        // TODO add your handling code here:
        computeBtn.setVisible(true);
        choose = 1;
    }// GEN-LAST:event_newEPActionPerformed

    private void fileEPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fileEPActionPerformed
        // TODO add your handling code here:
        computeBtn.setVisible(true);
        choose = 2;
    }// GEN-LAST:event_fileEPActionPerformed

    private void computeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_computeBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.setVisible(false);
        this.setContentPane(mainInputPanel);
        mainInputPanel.setVisible(true);
        resetInput();
        try {
            out.writeObject(choose);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Errore nell'invio dei dati", "Errore", JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_computeBtnActionPerformed

    private void resetInput() {

        startGroup.clearSelection();
        computeBtn.setVisible(false);
        choose = 0;
    }

    protected void resetMainPanel() {

        mainPanel.setVisible(true);
        this.setContentPane(mainPanel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWinClient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWinClient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWinClient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWinClient.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainWinClient().setVisible(true);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Errore: IOException", "Errore", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton computeBtn;
    private javax.swing.JRadioButton fileEP;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JRadioButton newEP;
    private javax.swing.ButtonGroup startGroup;
    private javax.swing.JLabel startLabel;
    // End of variables declaration//GEN-END:variables
}
