import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
/**
 *
 * @author User
 */
public class WinInput extends javax.swing.JPanel {

    private ObjectInputStream panelIn;
    private ObjectOutputStream panelOut;

    /**
     * Creates new form Win2
     */
    public WinInput(ObjectInputStream in, ObjectOutputStream out) {
        initComponents();
        panelIn = in;
        panelOut = out;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supLabel = new javax.swing.JLabel();
        inputMinSup = new javax.swing.JTextField();
        grLabel = new javax.swing.JLabel();
        inputGrowRate = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        targetLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();
        btnInput = new javax.swing.JButton();
        targetChoose = new javax.swing.JComboBox<>();
        backgroundChoose = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(600, 500));

        supLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        supLabel.setText(" Valore di minimo supporto ");

        grLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        grLabel.setText("Valore minimo di Grow Rate");

        targetLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        targetLabel.setText("Tabella Target");

        backgroundLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backgroundLabel.setText("Tabella Background");

        btnInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnInput.setForeground(new java.awt.Color(30, 0, 255));
        btnInput.setText("VAI!");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        targetChoose.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        targetChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "playtennistarget" }));

        backgroundChoose.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backgroundChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "playtennisBackground" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(backgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(backgroundChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(targetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(targetChoose, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(grLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(supLabel)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputGrowRate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputMinSup, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMinSup, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputGrowRate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(targetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(targetChoose)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInputActionPerformed

        String minSup = inputMinSup.getText();
        String minGrow = inputGrowRate.getText();
        //String targetTable = targetInput.getText();
        //String backgroundTable = backgroundInput.getText();

        float sentMinSup = -1;
        float sentMinGrow = -1;
        String sentTargetTable = (String) backgroundChoose.getSelectedItem();
        String sentBackgroundTable = (String) targetChoose.getSelectedItem();;

        if (minSup.equals("")) {
            JOptionPane.showMessageDialog(null, "Inserire un valore di minimo supporto", "Errore",
                    JOptionPane.ERROR_MESSAGE);
        } else {

            if (Utils.isNumber(minSup)) {

                if (Utils.getNumber(minSup) <= 0 || Utils.getNumber(minSup) > 1) {
                    JOptionPane.showMessageDialog(null, "Inserire un valore compreso tra 0 e 1", "Errore",
                            JOptionPane.ERROR_MESSAGE);
                    inputMinSup.setText("");
                } else {
                    sentMinSup = Utils.getNumber(minSup);
                }
            }
        }
        if (minGrow.equals("")) {
            JOptionPane.showMessageDialog(null, "Inserire un valore di grow rate", "Errore", JOptionPane.ERROR_MESSAGE);
        } else {

            if (Utils.isNumber(minGrow)) {

                if (Utils.getNumber(minGrow) <= 0) {
                    JOptionPane.showMessageDialog(null, "Inserire un valore strettamente maggiore di 0", "Errore",
                            JOptionPane.ERROR_MESSAGE);
                    inputGrowRate.setText("");
                } else {
                    sentMinGrow = Utils.getNumber(minGrow);
                }
            }
        }
       
        if ((sentMinSup > 0 && sentMinSup <= 1) && sentMinGrow > 0) {
            
            try{
                panelOut.writeObject(sentMinSup);
                panelOut.writeObject(sentMinGrow);
                panelOut.writeObject(sentTargetTable);
                panelOut.writeObject(sentBackgroundTable);

                String fpMiner = (String) (panelIn.readObject());
                String epMiner = (String) (panelIn.readObject());
                
                resetInput();
                this.setVisible(false);
                MainWinClient topFrame = (MainWinClient) SwingUtilities.getWindowAncestor(this);
                topFrame.resetMainPanel();
                
            WinOutEp dialog = new WinOutEp(new javax.swing.JFrame(), true, epMiner, fpMiner, sentMinSup, sentMinGrow, sentTargetTable, sentBackgroundTable, fpMiner, epMiner, panelOut);
               
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Errore invio dei dati ", "Qualcosa e' andato storto ",
                JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Errore invio dei dati ", "Qualcosa e' andato storto ",
                JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "I valori inseriti non sono validi ", "Qualcosa e' andato storto ",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnInputActionPerformed

    private void resetInput(){
        inputGrowRate.setText("");
        inputMinSup.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> backgroundChoose;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton btnInput;
    private javax.swing.JLabel grLabel;
    private javax.swing.JTextField inputGrowRate;
    private javax.swing.JTextField inputMinSup;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel supLabel;
    private javax.swing.JComboBox<String> targetChoose;
    private javax.swing.JLabel targetLabel;
    // End of variables declaration//GEN-END:variables
}
