/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package epminer_server;

public class App {
  

    public static void main(String[] args) {
        Data trainingSet = new Data();
        System.out.println(trainingSet);
    }
}
