/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapgui;

/**
 *
 * @author User
 */
public class StartPanel extends javax.swing.JPanel {

    /**
     * Creates new form StartPanel
     */
    public StartPanel() {
        initComponents();
        goBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainTitle = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        goBtn = new javax.swing.JToggleButton();
        newDiscoverBtn = new javax.swing.JRadioButton();
        archiveDiscoverBtn = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(500, 400));

        mainTitle.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(0, 30, 255));
        mainTitle.setText("    Benvenuto in EPMiner");
        mainTitle.setPreferredSize(new java.awt.Dimension(490, 350));

        label1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label1.setText("   Inizia subito!");

        goBtn.setText("VAI");
        goBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(newDiscoverBtn);
        newDiscoverBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        newDiscoverBtn.setText("Nuova Scoperta");
        newDiscoverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDiscoverBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(archiveDiscoverBtn);
        archiveDiscoverBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        archiveDiscoverBtn.setText("Scoperta in archivio");
        archiveDiscoverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archiveDiscoverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(goBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(archiveDiscoverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(newDiscoverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(newDiscoverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(archiveDiscoverBtn)
                .addGap(33, 33, 33)
                .addComponent(goBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
      
    }//GEN-LAST:event_goBtnActionPerformed

    private void newDiscoverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDiscoverBtnActionPerformed
        // TODO add your handling code here:
        goBtn.setVisible(true);
    }//GEN-LAST:event_newDiscoverBtnActionPerformed

    private void archiveDiscoverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archiveDiscoverBtnActionPerformed
        // TODO add your handling code here:
         goBtn.setVisible(true);
    }//GEN-LAST:event_archiveDiscoverBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton archiveDiscoverBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton goBtn;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JRadioButton newDiscoverBtn;
    // End of variables declaration//GEN-END:variables
}
